package cn.oyzh.easyshell.terminal.redis;

import cn.oyzh.easyshell.terminal.redis.acl.RedisAclCatTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.acl.RedisAclDeluserTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.acl.RedisAclDryrunTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.acl.RedisAclGenpassTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.acl.RedisAclGetuserTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.acl.RedisAclListTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.acl.RedisAclLoadTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.acl.RedisAclLogTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.acl.RedisAclSaveTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.acl.RedisAclSetuserTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.acl.RedisAclTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.acl.RedisAclUsersTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.acl.RedisAclWhoamiTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.base.RedisAuthTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.base.RedisConnectTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.base.RedisDelTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.base.RedisDumpTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.base.RedisEchoTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.base.RedisExistsTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.base.RedisFlushallTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.base.RedisFlushdbTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.base.RedisGetTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.base.RedisGetdelTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.base.RedisHelloTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.base.RedisKeysTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.base.RedisMigrateTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.base.RedisMoveTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.base.RedisPingTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.base.RedisRandomkeyTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.base.RedisRenameTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.base.RedisRenamenxTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.base.RedisRestoreTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.base.RedisSelectTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.base.RedisSetTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.base.RedisSwapdbTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.base.RedisTypeTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.base.RedisUnlinkTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.bit.RedisBitcountTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.bit.RedisBitfieldTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.bit.RedisBitfield_r0TerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.bit.RedisBitposTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.bit.RedisBittopTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.bit.RedisGetbitTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.bit.RedisSetbitTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.bit.RedisSetrangeTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.client.RedisClientCachingTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.client.RedisClientGetnameTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.client.RedisClientGetredirTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.client.RedisClientIdTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.client.RedisClientInfoTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.client.RedisClientKillTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.client.RedisClientListTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.client.RedisClientNoevictTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.client.RedisClientNotouchTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.client.RedisClientPuaseTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.client.RedisClientReplyTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.client.RedisClientSetinfoTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.client.RedisClientSetnameTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.client.RedisClientTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.client.RedisClientTrackingTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.client.RedisClientTrackinginfoTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.client.RedisClientUnblockTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.client.RedisClientUnpuaseTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.cluster.RedisClusterAddSlotsRangeTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.cluster.RedisClusterAddSlotsTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.cluster.RedisClusterBumpEpochTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.cluster.RedisClusterCountFailureReportsTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.cluster.RedisClusterCountKeysInSlotTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.cluster.RedisClusterDelSlotsRangeTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.cluster.RedisClusterDelSlotsTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.cluster.RedisClusterFailoverTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.cluster.RedisClusterFlushSlotsTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.cluster.RedisClusterForgetTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.cluster.RedisClusterGetKeysInSlotTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.cluster.RedisClusterInfoTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.cluster.RedisClusterKeyslotTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.cluster.RedisClusterLinksTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.cluster.RedisClusterMeetTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.cluster.RedisClusterMyShardIdTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.cluster.RedisClusterMyidTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.cluster.RedisClusterNodesTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.cluster.RedisClusterReplicateTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.cluster.RedisClusterResetTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.cluster.RedisClusterSaveConfigTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.cluster.RedisClusterSetConfigEpochTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.cluster.RedisClusterSetSlotTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.cluster.RedisClusterShardsTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.cluster.RedisClusterSlavesTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.cluster.RedisClusterSlotsTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.cluster.RedisClusterTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.command.RedisCommandCountTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.command.RedisCommandDocsTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.command.RedisCommandGetkeysTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.command.RedisCommandGetkeysandflagsTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.command.RedisCommandInfoTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.command.RedisCommandListTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.command.RedisCommandTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.geo.RedisGeoaddTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.geo.RedisGeodistTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.geo.RedisGeohashTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.geo.RedisGeoposTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.geo.RedisGeoradiusTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.geo.RedisGeoradius_r0TerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.geo.RedisGeoradiusbymemberTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.geo.RedisGeoradiusbymember_r0TerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.geo.RedisGeosearchTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.geo.RedisGeosearchstoreTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.hash.RedisHdelCommandHandler;
import cn.oyzh.easyshell.terminal.redis.hash.RedisHexistsCommandHandler;
import cn.oyzh.easyshell.terminal.redis.hash.RedisHgetCommandHandler;
import cn.oyzh.easyshell.terminal.redis.hash.RedisHgetallCommandHandler;
import cn.oyzh.easyshell.terminal.redis.hash.RedisHincrbyTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.hash.RedisHincrbyfloatTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.hash.RedisHkeysCommandHandler;
import cn.oyzh.easyshell.terminal.redis.hash.RedisHlenCommandHandler;
import cn.oyzh.easyshell.terminal.redis.hash.RedisHmgetCommandHandler;
import cn.oyzh.easyshell.terminal.redis.hash.RedisHrandfieldCommandHandler;
import cn.oyzh.easyshell.terminal.redis.hash.RedisHscanTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.hash.RedisHsetCommandHandler;
import cn.oyzh.easyshell.terminal.redis.hash.RedisHsetnxCommandHandler;
import cn.oyzh.easyshell.terminal.redis.hash.RedisHstrlenCommandHandler;
import cn.oyzh.easyshell.terminal.redis.hash.RedisHvalsCommandHandler;
import cn.oyzh.easyshell.terminal.redis.hylog.RedisPfaddTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.hylog.RedisPfcountTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.hylog.RedisPfmergeTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.key.RedisCopyTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.key.RedisDbSizeTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.key.RedisExpireTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.key.RedisExpireatTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.key.RedisExpiretimeTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.key.RedisGetexTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.key.RedisPersistTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.key.RedisPexpireTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.key.RedisPexpireatTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.key.RedisPexpiretimeTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.key.RedisPttlTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.key.RedisScanTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.key.RedisTtlTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.latency.RedisLatencyDoctorTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.latency.RedisLatencyGraphTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.latency.RedisLatencyHistogramTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.latency.RedisLatencyHistoryTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.latency.RedisLatencyLatestTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.latency.RedisLatencyResetTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.latency.RedisLatencyTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.list.RedisBlmoveTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.list.RedisBlmpopTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.list.RedisBlpopTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.list.RedisBrpopTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.list.RedisBrpoplpushTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.list.RedisLindexTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.list.RedisLinsertTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.list.RedisLlenTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.list.RedisLmoveTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.list.RedisLmpopTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.list.RedisLpopTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.list.RedisLposTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.list.RedisLpushTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.list.RedisLpushxTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.list.RedisLrangeTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.list.RedisLremTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.list.RedisLsetTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.list.RedisLtrimTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.list.RedisRpopTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.list.RedisRpoplpushTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.list.RedisRpushTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.list.RedisRpushxTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.memory.RedisMemoryDoctorTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.memory.RedisMemoryMallocstatsTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.memory.RedisMemoryPurgeTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.memory.RedisMemoryStatsTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.memory.RedisMemoryTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.memory.RedisMemoryUsageTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.module.RedisModuleListTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.module.RedisModuleLoadTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.module.RedisModuleLoadexTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.module.RedisModuleTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.module.RedisModuleUnloadTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.other.RedisAskingTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.other.RedisBgrewriteaofTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.other.RedisBgsaveTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.other.RedisFailoverTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.other.RedisLastsaveTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.other.RedisLolwutTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.other.RedisObjectTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.other.RedisReadonlyTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.other.RedisReadwriteTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.other.RedisReplicaofTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.other.RedisResetTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.other.RedisRoleTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.other.RedisSaveTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.other.RedisSlaveofTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.other.RedisTimeTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.other.RedisTouchTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.other.RedisWaitTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.other.RedisWaitaofTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.program.RedisEvalTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.program.RedisEval_r0TerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.program.RedisEvalshaTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.program.RedisEvalsha_r0TerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.program.RedisFcallTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.program.RedisFcall_r0TerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.program.function.RedisFunctionDeleteTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.program.function.RedisFunctionDumpTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.program.function.RedisFunctionFlushTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.program.function.RedisFunctionKillTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.program.function.RedisFunctionListTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.program.function.RedisFunctionLoadTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.program.function.RedisFunctionRestoreTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.program.function.RedisFunctionStatsTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.program.function.RedisFunctionTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.program.script.RedisScriptDebugTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.program.script.RedisScriptExistsTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.program.script.RedisScriptFlushTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.program.script.RedisScriptKillTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.program.script.RedisScriptLoadTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.program.script.RedisScriptTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.pubsub.RedisPsubscribeTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.pubsub.RedisPublishTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.pubsub.RedisPubsubTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.pubsub.RedisPunsubscribeTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.pubsub.RedisSpublishTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.pubsub.RedisSsubscribeTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.pubsub.RedisSubscribeTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.pubsub.RedisSunsubscribeTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.pubsub.RedisUnsubscribeTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.server.RedisDiscardTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.server.RedisExecTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.server.RedisInfoTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.server.RedisLcsTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.server.RedisMonitorTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.server.RedisMuiltTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.server.RedisShutdownTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.server.RedisSortTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.server.RedisSort_r0TerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.server.RedisUnwatchTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.server.RedisWatchTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.server.config.RedisConfigGetTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.server.config.RedisConfigResetStatTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.server.config.RedisConfigRewriteTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.server.config.RedisConfigSetTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.server.config.RedisConfigTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.set.RedisSaddTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.set.RedisScardTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.set.RedisSdiffTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.set.RedisSdiffstoreTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.set.RedisSinterTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.set.RedisSintercarkTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.set.RedisSinterstoreTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.set.RedisSismemberCommandHandler;
import cn.oyzh.easyshell.terminal.redis.set.RedisSmembersCommandHandler;
import cn.oyzh.easyshell.terminal.redis.set.RedisSmismemberCommandHandler;
import cn.oyzh.easyshell.terminal.redis.set.RedisSmoveTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.set.RedisSpopTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.set.RedisSrandmemberCommandHandler;
import cn.oyzh.easyshell.terminal.redis.set.RedisSremCommandHandler;
import cn.oyzh.easyshell.terminal.redis.set.RedisSscanTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.set.RedisSunionTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.set.RedisSunionstoreTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.slowlog.RedisSlowlogGetTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.slowlog.RedisSlowlogLenTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.slowlog.RedisSlowlogResetTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.slowlog.RedisSlowlogTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.stream.RedisXackTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.stream.RedisXaddTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.stream.RedisXautoclaimTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.stream.RedisXclaimTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.stream.RedisXdelTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.stream.RedisXlenTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.stream.RedisXpendingTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.stream.RedisXrangeTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.stream.RedisXreadTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.stream.RedisXreadgroupTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.stream.RedisXrevrangeTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.stream.RedisXtrimTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.stream.xgroup.RedisXgroupCreateTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.stream.xgroup.RedisXgroupCreateconsumerTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.stream.xgroup.RedisXgroupDelconsumerTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.stream.xgroup.RedisXgroupDestoryTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.stream.xgroup.RedisXgroupSetidTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.stream.xgroup.RedisXgroupTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.stream.xinfo.RedisXinfoConsumersTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.stream.xinfo.RedisXinfoGroupsTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.stream.xinfo.RedisXinfoStreamTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.stream.xinfo.RedisXinfoTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.string.RedisAppendTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.string.RedisDecrTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.string.RedisDecrbyTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.string.RedisGetsetTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.string.RedisIncrTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.string.RedisIncrbyTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.string.RedisIncrbyfloatTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.string.RedisMgetTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.string.RedisMsetTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.string.RedisMsetnxTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.string.RedisPsetnexTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.string.RedisSetexTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.string.RedisSetnxTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.string.RedisStrlenTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.string.RedisSubstrTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.zset.RedisBzmpopTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.zset.RedisBzpopmaxTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.zset.RedisBzpopminTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.zset.RedisZaddTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.zset.RedisZcardTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.zset.RedisZcountTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.zset.RedisZdiffTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.zset.RedisZdiffstoreTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.zset.RedisZincrbyTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.zset.RedisZinterTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.zset.RedisZintercardTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.zset.RedisZinterstoreTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.zset.RedisZlexcountTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.zset.RedisZmpopTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.zset.RedisZmscoreTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.zset.RedisZpopmaxTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.zset.RedisZpopminTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.zset.RedisZrandmemberCommandHandler;
import cn.oyzh.easyshell.terminal.redis.zset.RedisZrangeTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.zset.RedisZrangebylexTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.zset.RedisZrangebyscoreTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.zset.RedisZrangestoreTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.zset.RedisZrankTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.zset.RedisZremCommandHandler;
import cn.oyzh.easyshell.terminal.redis.zset.RedisZremrangebylexTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.zset.RedisZremrangebyrankTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.zset.RedisZremrangebyscoreTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.zset.RedisZrevrangeTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.zset.RedisZrevrangebylexTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.zset.RedisZrevrangebyscoreTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.zset.RedisZrevrankTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.zset.RedisZscanTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.zset.RedisZscoreTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.zset.RedisZunionTerminalCommandHandler;
import cn.oyzh.easyshell.terminal.redis.zset.RedisZunionstoreTerminalCommandHandler;
import cn.oyzh.fx.terminal.standard.ClearTerminalCommandHandler;
import cn.oyzh.fx.terminal.standard.HelpTerminalCommandHandler;
import cn.oyzh.fx.terminal.util.TerminalManager;

/**
 * @author oyzh
 * @since 2024-12-30
 */

public class RedisTerminalManager {

    /**
     * 注册处理器
     */
    public static void registerHandlers() {
        // 标准命令
        TerminalManager.registerHandler(HelpTerminalCommandHandler.class);
        TerminalManager.registerHandler(ClearTerminalCommandHandler.class);

        // acl命令
        TerminalManager.registerHandler(RedisAclCatTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisAclDeluserTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisAclDryrunTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisAclGenpassTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisAclGetuserTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisAclListTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisAclLoadTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisAclLogTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisAclSaveTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisAclSetuserTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisAclTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisAclUsersTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisAclWhoamiTerminalCommandHandler.class);

        // 基础命令
        TerminalManager.registerHandler(RedisAuthTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisConnectTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisDelTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisDumpTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisEchoTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisExistsTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisFlushallTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisFlushdbTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisGetdelTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisGetTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisHelloTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisKeysTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisMigrateTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisMoveTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisPingTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisRandomkeyTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisRenamenxTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisRenameTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisRestoreTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisSelectTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisSetTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisSwapdbTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisTypeTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisUnlinkTerminalCommandHandler.class);

        // bit命令
        TerminalManager.registerHandler(RedisBitcountTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisBitfield_r0TerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisBitfieldTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisBitposTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisBittopTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisGetbitTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisSetbitTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisSetrangeTerminalCommandHandler.class);

        // client命令
        TerminalManager.registerHandler(RedisClientCachingTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisClientGetnameTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisClientGetredirTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisClientIdTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisClientInfoTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisClientKillTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisClientListTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisClientNoevictTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisClientNotouchTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisClientPuaseTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisClientReplyTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisClientSetinfoTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisClientSetnameTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisClientTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisClientTrackinginfoTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisClientTrackingTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisClientUnblockTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisClientUnpuaseTerminalCommandHandler.class);

        // cluster命令
        TerminalManager.registerHandler(RedisClusterAddSlotsRangeTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisClusterAddSlotsTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisClusterBumpEpochTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisClusterCountFailureReportsTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisClusterCountKeysInSlotTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisClusterDelSlotsRangeTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisClusterDelSlotsTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisClusterFailoverTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisClusterFlushSlotsTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisClusterForgetTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisClusterGetKeysInSlotTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisClusterInfoTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisClusterKeyslotTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisClusterLinksTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisClusterMeetTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisClusterMyidTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisClusterMyShardIdTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisClusterNodesTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisClusterReplicateTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisClusterResetTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisClusterSaveConfigTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisClusterSetConfigEpochTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisClusterSetSlotTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisClusterShardsTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisClusterSlavesTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisClusterSlotsTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisClusterTerminalCommandHandler.class);

        // command命令
        TerminalManager.registerHandler(RedisCommandCountTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisCommandDocsTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisCommandGetkeysandflagsTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisCommandGetkeysTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisCommandInfoTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisCommandListTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisCommandTerminalCommandHandler.class);

        // geo命令
        TerminalManager.registerHandler(RedisGeoaddTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisGeodistTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisGeohashTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisGeoposTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisGeoradius_r0TerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisGeoradiusbymember_r0TerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisGeoradiusbymemberTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisGeoradiusTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisGeosearchstoreTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisGeosearchTerminalCommandHandler.class);

        // hash命令
        TerminalManager.registerHandler(RedisHdelCommandHandler.class);
        TerminalManager.registerHandler(RedisHexistsCommandHandler.class);
        TerminalManager.registerHandler(RedisHgetallCommandHandler.class);
        TerminalManager.registerHandler(RedisHgetCommandHandler.class);
        TerminalManager.registerHandler(RedisHincrbyfloatTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisHincrbyTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisHkeysCommandHandler.class);
        TerminalManager.registerHandler(RedisHlenCommandHandler.class);
        TerminalManager.registerHandler(RedisHmgetCommandHandler.class);
        TerminalManager.registerHandler(RedisHrandfieldCommandHandler.class);
        TerminalManager.registerHandler(RedisHscanTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisHsetCommandHandler.class);
        TerminalManager.registerHandler(RedisHsetnxCommandHandler.class);
        TerminalManager.registerHandler(RedisHstrlenCommandHandler.class);
        TerminalManager.registerHandler(RedisHvalsCommandHandler.class);

        // hylog命令
        TerminalManager.registerHandler(RedisPfaddTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisPfcountTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisPfmergeTerminalCommandHandler.class);

        // key命令
        TerminalManager.registerHandler(RedisCopyTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisDbSizeTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisExpireatTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisExpireTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisExpiretimeTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisGetexTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisPersistTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisPexpireatTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisPexpireTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisPexpiretimeTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisPttlTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisScanTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisTtlTerminalCommandHandler.class);

        // latency命令
        TerminalManager.registerHandler(RedisLatencyDoctorTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisLatencyGraphTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisLatencyHistogramTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisLatencyHistoryTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisLatencyLatestTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisLatencyResetTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisLatencyTerminalCommandHandler.class);

        // list命令
        TerminalManager.registerHandler(RedisBlmoveTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisBlmpopTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisBlpopTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisBrpoplpushTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisBrpopTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisLindexTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisLinsertTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisLlenTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisLmoveTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisLmpopTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisLpopTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisLposTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisLpushTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisLpushxTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisLrangeTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisLremTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisLsetTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisLtrimTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisRpoplpushTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisRpopTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisRpushTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisRpushxTerminalCommandHandler.class);

        // memory命令
        TerminalManager.registerHandler(RedisMemoryDoctorTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisMemoryMallocstatsTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisMemoryPurgeTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisMemoryStatsTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisMemoryTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisMemoryUsageTerminalCommandHandler.class);

        // module命令
        TerminalManager.registerHandler(RedisModuleListTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisModuleLoadexTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisModuleLoadTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisModuleTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisModuleUnloadTerminalCommandHandler.class);

        // other
        TerminalManager.registerHandler(RedisAskingTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisBgrewriteaofTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisBgsaveTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisFailoverTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisLastsaveTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisLolwutTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisObjectTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisReadonlyTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisReadwriteTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisReplicaofTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisResetTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisRoleTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisSaveTerminalCommandHandler.class);
        // TerminalManager.registerHandler(RedisSentinelTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisSlaveofTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisTimeTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisTouchTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisWaitaofTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisWaitTerminalCommandHandler.class);

        // program-function
        TerminalManager.registerHandler(RedisFunctionDeleteTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisFunctionDumpTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisFunctionFlushTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisFunctionKillTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisFunctionListTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisFunctionLoadTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisFunctionRestoreTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisFunctionStatsTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisFunctionTerminalCommandHandler.class);

        // program-script
        TerminalManager.registerHandler(RedisScriptDebugTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisScriptExistsTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisScriptFlushTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisScriptKillTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisScriptLoadTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisScriptTerminalCommandHandler.class);

        // program
        TerminalManager.registerHandler(RedisEval_r0TerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisEvalsha_r0TerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisEvalshaTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisEvalTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisFcall_r0TerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisFcallTerminalCommandHandler.class);

        // pubsub
        TerminalManager.registerHandler(RedisPsubscribeTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisPublishTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisPubsubTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisPunsubscribeTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisSpublishTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisSsubscribeTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisSubscribeTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisSunsubscribeTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisUnsubscribeTerminalCommandHandler.class);

        // server-config
        TerminalManager.registerHandler(RedisConfigGetTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisConfigResetStatTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisConfigRewriteTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisConfigSetTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisConfigTerminalCommandHandler.class);

        // server
        TerminalManager.registerHandler(RedisDiscardTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisExecTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisInfoTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisLcsTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisMonitorTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisMuiltTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisShutdownTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisSort_r0TerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisSortTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisUnwatchTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisWatchTerminalCommandHandler.class);

        // set
        TerminalManager.registerHandler(RedisSaddTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisScardTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisSdiffstoreTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisSdiffTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisSintercarkTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisSinterstoreTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisSinterTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisSismemberCommandHandler.class);
        TerminalManager.registerHandler(RedisSmembersCommandHandler.class);
        TerminalManager.registerHandler(RedisSmismemberCommandHandler.class);
        TerminalManager.registerHandler(RedisSmoveTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisSpopTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisSrandmemberCommandHandler.class);
        TerminalManager.registerHandler(RedisSremCommandHandler.class);
        TerminalManager.registerHandler(RedisSscanTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisSunionstoreTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisSunionTerminalCommandHandler.class);

        // slowlog命令
        TerminalManager.registerHandler(RedisSlowlogGetTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisSlowlogLenTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisSlowlogResetTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisSlowlogTerminalCommandHandler.class);

        // stream-xgroup
        TerminalManager.registerHandler(RedisXgroupCreateconsumerTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisXgroupCreateTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisXgroupDelconsumerTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisXgroupDestoryTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisXgroupSetidTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisXgroupTerminalCommandHandler.class);

        // stream-xinfo
        TerminalManager.registerHandler(RedisXinfoConsumersTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisXinfoGroupsTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisXinfoStreamTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisXinfoTerminalCommandHandler.class);

        // stream
        TerminalManager.registerHandler(RedisXackTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisXaddTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisXautoclaimTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisXclaimTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisXdelTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisXlenTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisXpendingTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisXrangeTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisXreadgroupTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisXreadTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisXrevrangeTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisXtrimTerminalCommandHandler.class);

        // string
        TerminalManager.registerHandler(RedisAppendTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisDecrbyTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisDecrTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisGetsetTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisIncrbyfloatTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisIncrbyTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisIncrTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisMgetTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisMsetnxTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisMsetTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisPsetnexTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisSetexTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisSetnxTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisStrlenTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisSubstrTerminalCommandHandler.class);

        // zset
        TerminalManager.registerHandler(RedisBzmpopTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisBzpopmaxTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisBzpopminTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisZaddTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisZcardTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisZcountTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisZdiffstoreTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisZdiffTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisZincrbyTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisZintercardTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisZinterstoreTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisZinterTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisZlexcountTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisZmpopTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisZmscoreTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisZpopmaxTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisZpopminTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisZrandmemberCommandHandler.class);
        TerminalManager.registerHandler(RedisZrangebylexTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisZrangebyscoreTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisZrangestoreTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisZrangeTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisZrankTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisZremCommandHandler.class);
        TerminalManager.registerHandler(RedisZremrangebylexTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisZremrangebyrankTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisZremrangebyscoreTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisZrevrangebylexTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisZrevrangebyscoreTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisZrevrangeTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisZrevrankTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisZscanTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisZscoreTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisZunionstoreTerminalCommandHandler.class);
        TerminalManager.registerHandler(RedisZunionTerminalCommandHandler.class);
    }
}
