// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: transportinstruction.proto
// Protobuf Java Version: 4.35.1

package org.mosh4j.protocol.transport;

@com.google.protobuf.Generated
public final class Transportinstruction extends com.google.protobuf.GeneratedFile {
  private Transportinstruction() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 1,
      /* suffix= */ "",
      "Transportinstruction");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface InstructionOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.mosh4j.protocol.transport.Instruction)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional uint32 protocol_version = 1;</code>
     * @return Whether the protocolVersion field is set.
     */
    boolean hasProtocolVersion();
    /**
     * <code>optional uint32 protocol_version = 1;</code>
     * @return The protocolVersion.
     */
    int getProtocolVersion();

    /**
     * <code>optional uint64 old_num = 2;</code>
     * @return Whether the oldNum field is set.
     */
    boolean hasOldNum();
    /**
     * <code>optional uint64 old_num = 2;</code>
     * @return The oldNum.
     */
    long getOldNum();

    /**
     * <code>optional uint64 new_num = 3;</code>
     * @return Whether the newNum field is set.
     */
    boolean hasNewNum();
    /**
     * <code>optional uint64 new_num = 3;</code>
     * @return The newNum.
     */
    long getNewNum();

    /**
     * <code>optional uint64 ack_num = 4;</code>
     * @return Whether the ackNum field is set.
     */
    boolean hasAckNum();
    /**
     * <code>optional uint64 ack_num = 4;</code>
     * @return The ackNum.
     */
    long getAckNum();

    /**
     * <code>optional uint64 throwaway_num = 5;</code>
     * @return Whether the throwawayNum field is set.
     */
    boolean hasThrowawayNum();
    /**
     * <code>optional uint64 throwaway_num = 5;</code>
     * @return The throwawayNum.
     */
    long getThrowawayNum();

    /**
     * <code>optional bytes diff = 6;</code>
     * @return Whether the diff field is set.
     */
    boolean hasDiff();
    /**
     * <code>optional bytes diff = 6;</code>
     * @return The diff.
     */
    com.google.protobuf.ByteString getDiff();

    /**
     * <code>optional bytes chaff = 7;</code>
     * @return Whether the chaff field is set.
     */
    boolean hasChaff();
    /**
     * <code>optional bytes chaff = 7;</code>
     * @return The chaff.
     */
    com.google.protobuf.ByteString getChaff();
  }
  /**
   * Protobuf type {@code org.mosh4j.protocol.transport.Instruction}
   */
  public static final class Instruction extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:org.mosh4j.protocol.transport.Instruction)
      InstructionOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 35,
        /* patch= */ 1,
        /* suffix= */ "",
        "Instruction");
    }
    // Use Instruction.newBuilder() to construct.
    private Instruction(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Instruction() {
      diff_ = com.google.protobuf.ByteString.EMPTY;
      chaff_ = com.google.protobuf.ByteString.EMPTY;
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Transportinstruction.internal_static_org_mosh4j_protocol_transport_Instruction_descriptor;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
      return Transportinstruction.internal_static_org_mosh4j_protocol_transport_Instruction_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Transportinstruction.internal_static_org_mosh4j_protocol_transport_Instruction_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Instruction.class, Builder.class);
    }

    private int bitField0_;
    public static final int PROTOCOL_VERSION_FIELD_NUMBER = 1;
    private int protocolVersion_ = 0;
    /**
     * <code>optional uint32 protocol_version = 1;</code>
     * @return Whether the protocolVersion field is set.
     */
    @Override
    public boolean hasProtocolVersion() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional uint32 protocol_version = 1;</code>
     * @return The protocolVersion.
     */
    @Override
    public int getProtocolVersion() {
      return protocolVersion_;
    }

    public static final int OLD_NUM_FIELD_NUMBER = 2;
    private long oldNum_ = 0L;
    /**
     * <code>optional uint64 old_num = 2;</code>
     * @return Whether the oldNum field is set.
     */
    @Override
    public boolean hasOldNum() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional uint64 old_num = 2;</code>
     * @return The oldNum.
     */
    @Override
    public long getOldNum() {
      return oldNum_;
    }

    public static final int NEW_NUM_FIELD_NUMBER = 3;
    private long newNum_ = 0L;
    /**
     * <code>optional uint64 new_num = 3;</code>
     * @return Whether the newNum field is set.
     */
    @Override
    public boolean hasNewNum() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional uint64 new_num = 3;</code>
     * @return The newNum.
     */
    @Override
    public long getNewNum() {
      return newNum_;
    }

    public static final int ACK_NUM_FIELD_NUMBER = 4;
    private long ackNum_ = 0L;
    /**
     * <code>optional uint64 ack_num = 4;</code>
     * @return Whether the ackNum field is set.
     */
    @Override
    public boolean hasAckNum() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional uint64 ack_num = 4;</code>
     * @return The ackNum.
     */
    @Override
    public long getAckNum() {
      return ackNum_;
    }

    public static final int THROWAWAY_NUM_FIELD_NUMBER = 5;
    private long throwawayNum_ = 0L;
    /**
     * <code>optional uint64 throwaway_num = 5;</code>
     * @return Whether the throwawayNum field is set.
     */
    @Override
    public boolean hasThrowawayNum() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional uint64 throwaway_num = 5;</code>
     * @return The throwawayNum.
     */
    @Override
    public long getThrowawayNum() {
      return throwawayNum_;
    }

    public static final int DIFF_FIELD_NUMBER = 6;
    private com.google.protobuf.ByteString diff_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>optional bytes diff = 6;</code>
     * @return Whether the diff field is set.
     */
    @Override
    public boolean hasDiff() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>optional bytes diff = 6;</code>
     * @return The diff.
     */
    @Override
    public com.google.protobuf.ByteString getDiff() {
      return diff_;
    }

    public static final int CHAFF_FIELD_NUMBER = 7;
    private com.google.protobuf.ByteString chaff_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>optional bytes chaff = 7;</code>
     * @return Whether the chaff field is set.
     */
    @Override
    public boolean hasChaff() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <code>optional bytes chaff = 7;</code>
     * @return The chaff.
     */
    @Override
    public com.google.protobuf.ByteString getChaff() {
      return chaff_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeUInt32(1, protocolVersion_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeUInt64(2, oldNum_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeUInt64(3, newNum_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        output.writeUInt64(4, ackNum_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        output.writeUInt64(5, throwawayNum_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        output.writeBytes(6, diff_);
      }
      if (((bitField0_ & 0x00000040) != 0)) {
        output.writeBytes(7, chaff_);
      }
      getUnknownFields().writeTo(output);
    }
    private int computeSerializedSize_0() {
      int size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, protocolVersion_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(2, oldNum_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(3, newNum_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(4, ackNum_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(5, throwawayNum_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, diff_);
      }
      if (((bitField0_ & 0x00000040) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, chaff_);
      }
      return size;
    }
    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += computeSerializedSize_0();
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Instruction)) {
        return super.equals(obj);
      }
      Instruction other = (Instruction) obj;

      if (hasProtocolVersion() != other.hasProtocolVersion()) return false;
      if (hasProtocolVersion()) {
        if (getProtocolVersion()
            != other.getProtocolVersion()) return false;
      }
      if (hasOldNum() != other.hasOldNum()) return false;
      if (hasOldNum()) {
        if (getOldNum()
            != other.getOldNum()) return false;
      }
      if (hasNewNum() != other.hasNewNum()) return false;
      if (hasNewNum()) {
        if (getNewNum()
            != other.getNewNum()) return false;
      }
      if (hasAckNum() != other.hasAckNum()) return false;
      if (hasAckNum()) {
        if (getAckNum()
            != other.getAckNum()) return false;
      }
      if (hasThrowawayNum() != other.hasThrowawayNum()) return false;
      if (hasThrowawayNum()) {
        if (getThrowawayNum()
            != other.getThrowawayNum()) return false;
      }
      if (hasDiff() != other.hasDiff()) return false;
      if (hasDiff()) {
        if (!getDiff()
            .equals(other.getDiff())) return false;
      }
      if (hasChaff() != other.hasChaff()) return false;
      if (hasChaff()) {
        if (!getChaff()
            .equals(other.getChaff())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasProtocolVersion()) {
        hash = (37 * hash) + PROTOCOL_VERSION_FIELD_NUMBER;
        hash = (53 * hash) + getProtocolVersion();
      }
      if (hasOldNum()) {
        hash = (37 * hash) + OLD_NUM_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getOldNum());
      }
      if (hasNewNum()) {
        hash = (37 * hash) + NEW_NUM_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getNewNum());
      }
      if (hasAckNum()) {
        hash = (37 * hash) + ACK_NUM_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getAckNum());
      }
      if (hasThrowawayNum()) {
        hash = (37 * hash) + THROWAWAY_NUM_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getThrowawayNum());
      }
      if (hasDiff()) {
        hash = (37 * hash) + DIFF_FIELD_NUMBER;
        hash = (53 * hash) + getDiff().hashCode();
      }
      if (hasChaff()) {
        hash = (37 * hash) + CHAFF_FIELD_NUMBER;
        hash = (53 * hash) + getChaff().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Instruction parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Instruction parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Instruction parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Instruction parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Instruction parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Instruction parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Instruction parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static Instruction parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static Instruction parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static Instruction parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Instruction parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static Instruction parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Instruction prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.mosh4j.protocol.transport.Instruction}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.mosh4j.protocol.transport.Instruction)
        InstructionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Transportinstruction.internal_static_org_mosh4j_protocol_transport_Instruction_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Transportinstruction.internal_static_org_mosh4j_protocol_transport_Instruction_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Instruction.class, Builder.class);
      }

      // Construct using org.mosh4j.protocol.transport.Transportinstruction.Instruction.newBuilder()
      private Builder() {

      }

      private Builder(
          BuilderParent parent) {
        super(parent);

      }
      @Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        protocolVersion_ = 0;
        oldNum_ = 0L;
        newNum_ = 0L;
        ackNum_ = 0L;
        throwawayNum_ = 0L;
        diff_ = com.google.protobuf.ByteString.EMPTY;
        chaff_ = com.google.protobuf.ByteString.EMPTY;
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Transportinstruction.internal_static_org_mosh4j_protocol_transport_Instruction_descriptor;
      }

      @Override
      public Instruction getDefaultInstanceForType() {
        return Instruction.getDefaultInstance();
      }

      @Override
      public Instruction build() {
        Instruction result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public Instruction buildPartial() {
        Instruction result = new Instruction(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(Instruction result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.protocolVersion_ = protocolVersion_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.oldNum_ = oldNum_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.newNum_ = newNum_;
          to_bitField0_ |= 0x00000004;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.ackNum_ = ackNum_;
          to_bitField0_ |= 0x00000008;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.throwawayNum_ = throwawayNum_;
          to_bitField0_ |= 0x00000010;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.diff_ = diff_;
          to_bitField0_ |= 0x00000020;
        }
        if (((from_bitField0_ & 0x00000040) != 0)) {
          result.chaff_ = chaff_;
          to_bitField0_ |= 0x00000040;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Instruction) {
          return mergeFrom((Instruction)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Instruction other) {
        if (other == Instruction.getDefaultInstance()) return this;
        if (other.hasProtocolVersion()) {
          setProtocolVersion(other.getProtocolVersion());
        }
        if (other.hasOldNum()) {
          setOldNum(other.getOldNum());
        }
        if (other.hasNewNum()) {
          setNewNum(other.getNewNum());
        }
        if (other.hasAckNum()) {
          setAckNum(other.getAckNum());
        }
        if (other.hasThrowawayNum()) {
          setThrowawayNum(other.getThrowawayNum());
        }
        if (other.hasDiff()) {
          setDiff(other.getDiff());
        }
        if (other.hasChaff()) {
          setChaff(other.getChaff());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                protocolVersion_ = input.readUInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 16: {
                oldNum_ = input.readUInt64();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 24: {
                newNum_ = input.readUInt64();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              case 32: {
                ackNum_ = input.readUInt64();
                bitField0_ |= 0x00000008;
                break;
              } // case 32
              case 40: {
                throwawayNum_ = input.readUInt64();
                bitField0_ |= 0x00000010;
                break;
              } // case 40
              case 50: {
                diff_ = input.readBytes();
                bitField0_ |= 0x00000020;
                break;
              } // case 50
              case 58: {
                chaff_ = input.readBytes();
                bitField0_ |= 0x00000040;
                break;
              } // case 58
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int protocolVersion_ ;
      /**
       * <code>optional uint32 protocol_version = 1;</code>
       * @return Whether the protocolVersion field is set.
       */
      @Override
      public boolean hasProtocolVersion() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional uint32 protocol_version = 1;</code>
       * @return The protocolVersion.
       */
      @Override
      public int getProtocolVersion() {
        return protocolVersion_;
      }
      /**
       * <code>optional uint32 protocol_version = 1;</code>
       * @param value The protocolVersion to set.
       * @return This builder for chaining.
       */
      public Builder setProtocolVersion(int value) {

        protocolVersion_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 protocol_version = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearProtocolVersion() {
        bitField0_ = (bitField0_ & ~0x00000001);
        protocolVersion_ = 0;
        onChanged();
        return this;
      }

      private long oldNum_ ;
      /**
       * <code>optional uint64 old_num = 2;</code>
       * @return Whether the oldNum field is set.
       */
      @Override
      public boolean hasOldNum() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional uint64 old_num = 2;</code>
       * @return The oldNum.
       */
      @Override
      public long getOldNum() {
        return oldNum_;
      }
      /**
       * <code>optional uint64 old_num = 2;</code>
       * @param value The oldNum to set.
       * @return This builder for chaining.
       */
      public Builder setOldNum(long value) {

        oldNum_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 old_num = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearOldNum() {
        bitField0_ = (bitField0_ & ~0x00000002);
        oldNum_ = 0L;
        onChanged();
        return this;
      }

      private long newNum_ ;
      /**
       * <code>optional uint64 new_num = 3;</code>
       * @return Whether the newNum field is set.
       */
      @Override
      public boolean hasNewNum() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional uint64 new_num = 3;</code>
       * @return The newNum.
       */
      @Override
      public long getNewNum() {
        return newNum_;
      }
      /**
       * <code>optional uint64 new_num = 3;</code>
       * @param value The newNum to set.
       * @return This builder for chaining.
       */
      public Builder setNewNum(long value) {

        newNum_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 new_num = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearNewNum() {
        bitField0_ = (bitField0_ & ~0x00000004);
        newNum_ = 0L;
        onChanged();
        return this;
      }

      private long ackNum_ ;
      /**
       * <code>optional uint64 ack_num = 4;</code>
       * @return Whether the ackNum field is set.
       */
      @Override
      public boolean hasAckNum() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>optional uint64 ack_num = 4;</code>
       * @return The ackNum.
       */
      @Override
      public long getAckNum() {
        return ackNum_;
      }
      /**
       * <code>optional uint64 ack_num = 4;</code>
       * @param value The ackNum to set.
       * @return This builder for chaining.
       */
      public Builder setAckNum(long value) {

        ackNum_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 ack_num = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearAckNum() {
        bitField0_ = (bitField0_ & ~0x00000008);
        ackNum_ = 0L;
        onChanged();
        return this;
      }

      private long throwawayNum_ ;
      /**
       * <code>optional uint64 throwaway_num = 5;</code>
       * @return Whether the throwawayNum field is set.
       */
      @Override
      public boolean hasThrowawayNum() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <code>optional uint64 throwaway_num = 5;</code>
       * @return The throwawayNum.
       */
      @Override
      public long getThrowawayNum() {
        return throwawayNum_;
      }
      /**
       * <code>optional uint64 throwaway_num = 5;</code>
       * @param value The throwawayNum to set.
       * @return This builder for chaining.
       */
      public Builder setThrowawayNum(long value) {

        throwawayNum_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 throwaway_num = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearThrowawayNum() {
        bitField0_ = (bitField0_ & ~0x00000010);
        throwawayNum_ = 0L;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString diff_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes diff = 6;</code>
       * @return Whether the diff field is set.
       */
      @Override
      public boolean hasDiff() {
        return ((bitField0_ & 0x00000020) != 0);
      }
      /**
       * <code>optional bytes diff = 6;</code>
       * @return The diff.
       */
      @Override
      public com.google.protobuf.ByteString getDiff() {
        return diff_;
      }
      /**
       * <code>optional bytes diff = 6;</code>
       * @param value The diff to set.
       * @return This builder for chaining.
       */
      public Builder setDiff(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        diff_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes diff = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearDiff() {
        bitField0_ = (bitField0_ & ~0x00000020);
        diff_ = getDefaultInstance().getDiff();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString chaff_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes chaff = 7;</code>
       * @return Whether the chaff field is set.
       */
      @Override
      public boolean hasChaff() {
        return ((bitField0_ & 0x00000040) != 0);
      }
      /**
       * <code>optional bytes chaff = 7;</code>
       * @return The chaff.
       */
      @Override
      public com.google.protobuf.ByteString getChaff() {
        return chaff_;
      }
      /**
       * <code>optional bytes chaff = 7;</code>
       * @param value The chaff to set.
       * @return This builder for chaining.
       */
      public Builder setChaff(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        chaff_ = value;
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes chaff = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearChaff() {
        bitField0_ = (bitField0_ & ~0x00000040);
        chaff_ = getDefaultInstance().getChaff();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:org.mosh4j.protocol.transport.Instruction)
    }

    // @@protoc_insertion_point(class_scope:org.mosh4j.protocol.transport.Instruction)
    private static final Instruction DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Instruction();
    }

    public static Instruction getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Instruction>
        PARSER = new com.google.protobuf.AbstractParser<Instruction>() {
      @Override
      public Instruction parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Instruction> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Instruction> getParserForType() {
      return PARSER;
    }

    @Override
    public Instruction getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_mosh4j_protocol_transport_Instruction_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_mosh4j_protocol_transport_Instruction_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static final com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\032transportinstruction.proto\022\035org.mosh4j" +
      ".protocol.transport\"\216\001\n\013Instruction\022\030\n\020p" +
      "rotocol_version\030\001 \001(\r\022\017\n\007old_num\030\002 \001(\004\022\017" +
      "\n\007new_num\030\003 \001(\004\022\017\n\007ack_num\030\004 \001(\004\022\025\n\rthro" +
      "waway_num\030\005 \001(\004\022\014\n\004diff\030\006 \001(\014\022\r\n\005chaff\030\007" +
      " \001(\014B\002H\003"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_org_mosh4j_protocol_transport_Instruction_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_org_mosh4j_protocol_transport_Instruction_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_org_mosh4j_protocol_transport_Instruction_descriptor,
        new String[] { "ProtocolVersion", "OldNum", "NewNum", "AckNum", "ThrowawayNum", "Diff", "Chaff", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
