version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: mongo-tls
    ports:
      - "27019:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: mongo@2026
    volumes:
      - ./ca.crt:/etc/ssl/ca.crt
      - ./mongo.pem:/etc/ssl/mongo.pem
      - ./mongod.conf:/etc/mongod.conf
    command: ["mongod", "--config", "/etc/mongod.conf"]