// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: hostinput.proto
// Protobuf Java Version: 4.35.1

package org.mosh4j.protocol.host;

@com.google.protobuf.Generated
public final class Hostinput extends com.google.protobuf.GeneratedFile {
  private Hostinput() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 1,
      /* suffix= */ "",
      "Hostinput");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
    registry.add(Hostinput.hostbytes);
    registry.add(Hostinput.resize);
    registry.add(Hostinput.echoack);
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface HostMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.mosh4j.protocol.host.HostMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .org.mosh4j.protocol.host.Instruction instruction = 1;</code>
     */
    java.util.List<Instruction>
        getInstructionList();
    /**
     * <code>repeated .org.mosh4j.protocol.host.Instruction instruction = 1;</code>
     */
    Instruction getInstruction(int index);
    /**
     * <code>repeated .org.mosh4j.protocol.host.Instruction instruction = 1;</code>
     */
    int getInstructionCount();
    /**
     * <code>repeated .org.mosh4j.protocol.host.Instruction instruction = 1;</code>
     */
    java.util.List<? extends InstructionOrBuilder>
        getInstructionOrBuilderList();
    /**
     * <code>repeated .org.mosh4j.protocol.host.Instruction instruction = 1;</code>
     */
    InstructionOrBuilder getInstructionOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code org.mosh4j.protocol.host.HostMessage}
   */
  public static final class HostMessage extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:org.mosh4j.protocol.host.HostMessage)
      HostMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 35,
        /* patch= */ 1,
        /* suffix= */ "",
        "HostMessage");
    }
    // Use HostMessage.newBuilder() to construct.
    private HostMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private HostMessage() {
      instruction_ = java.util.Collections.emptyList();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Hostinput.internal_static_org_mosh4j_protocol_host_HostMessage_descriptor;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
      return Hostinput.internal_static_org_mosh4j_protocol_host_HostMessage_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Hostinput.internal_static_org_mosh4j_protocol_host_HostMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              HostMessage.class, Builder.class);
    }

    public static final int INSTRUCTION_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private java.util.List<Instruction> instruction_;
    /**
     * <code>repeated .org.mosh4j.protocol.host.Instruction instruction = 1;</code>
     */
    @Override
    public java.util.List<Instruction> getInstructionList() {
      return instruction_;
    }
    /**
     * <code>repeated .org.mosh4j.protocol.host.Instruction instruction = 1;</code>
     */
    @Override
    public java.util.List<? extends InstructionOrBuilder>
        getInstructionOrBuilderList() {
      return instruction_;
    }
    /**
     * <code>repeated .org.mosh4j.protocol.host.Instruction instruction = 1;</code>
     */
    @Override
    public int getInstructionCount() {
      return instruction_.size();
    }
    /**
     * <code>repeated .org.mosh4j.protocol.host.Instruction instruction = 1;</code>
     */
    @Override
    public Instruction getInstruction(int index) {
      return instruction_.get(index);
    }
    /**
     * <code>repeated .org.mosh4j.protocol.host.Instruction instruction = 1;</code>
     */
    @Override
    public InstructionOrBuilder getInstructionOrBuilder(
        int index) {
      return instruction_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      for (int i = 0; i < getInstructionCount(); i++) {
        if (!getInstruction(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < instruction_.size(); i++) {
        output.writeMessage(1, instruction_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    private int computeSerializedSize_0() {
      int size = 0;

          {
            final int count = instruction_.size();
            for (int i = 0; i < count; i++) {
              size += com.google.protobuf.CodedOutputStream
                .computeMessageSizeNoTag(instruction_.get(i));
            }
            size += 1 * count;
          }
      return size;
    }
    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += computeSerializedSize_0();
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof HostMessage)) {
        return super.equals(obj);
      }
      HostMessage other = (HostMessage) obj;

      if (!getInstructionList()
          .equals(other.getInstructionList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getInstructionCount() > 0) {
        hash = (37 * hash) + INSTRUCTION_FIELD_NUMBER;
        hash = (53 * hash) + getInstructionList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static HostMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static HostMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static HostMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static HostMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static HostMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static HostMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static HostMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static HostMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static HostMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static HostMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static HostMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static HostMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(HostMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.mosh4j.protocol.host.HostMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.mosh4j.protocol.host.HostMessage)
        HostMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Hostinput.internal_static_org_mosh4j_protocol_host_HostMessage_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Hostinput.internal_static_org_mosh4j_protocol_host_HostMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                HostMessage.class, Builder.class);
      }

      // Construct using org.mosh4j.protocol.host.Hostinput.HostMessage.newBuilder()
      private Builder() {

      }

      private Builder(
          BuilderParent parent) {
        super(parent);

      }
      @Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        if (instructionBuilder_ == null) {
          instruction_ = java.util.Collections.emptyList();
        } else {
          instruction_ = null;
          instructionBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Hostinput.internal_static_org_mosh4j_protocol_host_HostMessage_descriptor;
      }

      @Override
      public HostMessage getDefaultInstanceForType() {
        return HostMessage.getDefaultInstance();
      }

      @Override
      public HostMessage build() {
        HostMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public HostMessage buildPartial() {
        HostMessage result = new HostMessage(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(HostMessage result) {
        if (instructionBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            instruction_ = java.util.Collections.unmodifiableList(instruction_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.instruction_ = instruction_;
        } else {
          result.instruction_ = instructionBuilder_.build();
        }
      }

      private void buildPartial0(HostMessage result) {
        int from_bitField0_ = bitField0_;
      }

      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof HostMessage) {
          return mergeFrom((HostMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(HostMessage other) {
        if (other == HostMessage.getDefaultInstance()) return this;
        if (instructionBuilder_ == null) {
          if (!other.instruction_.isEmpty()) {
            if (instruction_.isEmpty()) {
              instruction_ = other.instruction_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureInstructionIsMutable();
              instruction_.addAll(other.instruction_);
            }
            onChanged();
          }
        } else {
          if (!other.instruction_.isEmpty()) {
            if (instructionBuilder_.isEmpty()) {
              instructionBuilder_.dispose();
              instructionBuilder_ = null;
              instruction_ = other.instruction_;
              bitField0_ = (bitField0_ & ~0x00000001);
              instructionBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   internalGetInstructionFieldBuilder() : null;
            } else {
              instructionBuilder_.addAllMessages(other.instruction_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        for (int i = 0; i < getInstructionCount(); i++) {
          if (!getInstruction(i).isInitialized()) {
            return false;
          }
        }
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                Instruction m =
                    input.readMessage(
                        Instruction.parser(),
                        extensionRegistry);
                if (instructionBuilder_ == null) {
                  ensureInstructionIsMutable();
                  instruction_.add(m);
                } else {
                  instructionBuilder_.addMessage(m);
                }
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.util.List<Instruction> instruction_ =
        java.util.Collections.emptyList();
      private void ensureInstructionIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          instruction_ = new java.util.ArrayList<Instruction>(instruction_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          Instruction, Instruction.Builder, InstructionOrBuilder> instructionBuilder_;

      /**
       * <code>repeated .org.mosh4j.protocol.host.Instruction instruction = 1;</code>
       */
      public java.util.List<Instruction> getInstructionList() {
        if (instructionBuilder_ == null) {
          return java.util.Collections.unmodifiableList(instruction_);
        } else {
          return instructionBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .org.mosh4j.protocol.host.Instruction instruction = 1;</code>
       */
      public int getInstructionCount() {
        if (instructionBuilder_ == null) {
          return instruction_.size();
        } else {
          return instructionBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .org.mosh4j.protocol.host.Instruction instruction = 1;</code>
       */
      public Instruction getInstruction(int index) {
        if (instructionBuilder_ == null) {
          return instruction_.get(index);
        } else {
          return instructionBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .org.mosh4j.protocol.host.Instruction instruction = 1;</code>
       */
      public Builder setInstruction(
          int index, Instruction value) {
        if (instructionBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureInstructionIsMutable();
          instruction_.set(index, value);
          onChanged();
        } else {
          instructionBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .org.mosh4j.protocol.host.Instruction instruction = 1;</code>
       */
      public Builder setInstruction(
          int index, Instruction.Builder builderForValue) {
        if (instructionBuilder_ == null) {
          ensureInstructionIsMutable();
          instruction_.set(index, builderForValue.build());
          onChanged();
        } else {
          instructionBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .org.mosh4j.protocol.host.Instruction instruction = 1;</code>
       */
      public Builder addInstruction(Instruction value) {
        if (instructionBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureInstructionIsMutable();
          instruction_.add(value);
          onChanged();
        } else {
          instructionBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .org.mosh4j.protocol.host.Instruction instruction = 1;</code>
       */
      public Builder addInstruction(
          int index, Instruction value) {
        if (instructionBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureInstructionIsMutable();
          instruction_.add(index, value);
          onChanged();
        } else {
          instructionBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .org.mosh4j.protocol.host.Instruction instruction = 1;</code>
       */
      public Builder addInstruction(
          Instruction.Builder builderForValue) {
        if (instructionBuilder_ == null) {
          ensureInstructionIsMutable();
          instruction_.add(builderForValue.build());
          onChanged();
        } else {
          instructionBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .org.mosh4j.protocol.host.Instruction instruction = 1;</code>
       */
      public Builder addInstruction(
          int index, Instruction.Builder builderForValue) {
        if (instructionBuilder_ == null) {
          ensureInstructionIsMutable();
          instruction_.add(index, builderForValue.build());
          onChanged();
        } else {
          instructionBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .org.mosh4j.protocol.host.Instruction instruction = 1;</code>
       */
      public Builder addAllInstruction(
          Iterable<? extends Instruction> values) {
        if (instructionBuilder_ == null) {
          ensureInstructionIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, instruction_);
          onChanged();
        } else {
          instructionBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .org.mosh4j.protocol.host.Instruction instruction = 1;</code>
       */
      public Builder clearInstruction() {
        if (instructionBuilder_ == null) {
          instruction_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          instructionBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .org.mosh4j.protocol.host.Instruction instruction = 1;</code>
       */
      public Builder removeInstruction(int index) {
        if (instructionBuilder_ == null) {
          ensureInstructionIsMutable();
          instruction_.remove(index);
          onChanged();
        } else {
          instructionBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .org.mosh4j.protocol.host.Instruction instruction = 1;</code>
       */
      public Instruction.Builder getInstructionBuilder(
          int index) {
        return internalGetInstructionFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .org.mosh4j.protocol.host.Instruction instruction = 1;</code>
       */
      public InstructionOrBuilder getInstructionOrBuilder(
          int index) {
        if (instructionBuilder_ == null) {
          return instruction_.get(index);  } else {
          return instructionBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .org.mosh4j.protocol.host.Instruction instruction = 1;</code>
       */
      public java.util.List<? extends InstructionOrBuilder>
           getInstructionOrBuilderList() {
        if (instructionBuilder_ != null) {
          return instructionBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(instruction_);
        }
      }
      /**
       * <code>repeated .org.mosh4j.protocol.host.Instruction instruction = 1;</code>
       */
      public Instruction.Builder addInstructionBuilder() {
        return internalGetInstructionFieldBuilder().addBuilder(
            Instruction.getDefaultInstance());
      }
      /**
       * <code>repeated .org.mosh4j.protocol.host.Instruction instruction = 1;</code>
       */
      public Instruction.Builder addInstructionBuilder(
          int index) {
        return internalGetInstructionFieldBuilder().addBuilder(
            index, Instruction.getDefaultInstance());
      }
      /**
       * <code>repeated .org.mosh4j.protocol.host.Instruction instruction = 1;</code>
       */
      public java.util.List<Instruction.Builder>
           getInstructionBuilderList() {
        return internalGetInstructionFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          Instruction, Instruction.Builder, InstructionOrBuilder>
          internalGetInstructionFieldBuilder() {
        if (instructionBuilder_ == null) {
          instructionBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              Instruction, Instruction.Builder, InstructionOrBuilder>(
                  instruction_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          instruction_ = null;
        }
        return instructionBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:org.mosh4j.protocol.host.HostMessage)
    }

    // @@protoc_insertion_point(class_scope:org.mosh4j.protocol.host.HostMessage)
    private static final HostMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new HostMessage();
    }

    public static HostMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<HostMessage>
        PARSER = new com.google.protobuf.AbstractParser<HostMessage>() {
      @Override
      public HostMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<HostMessage> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<HostMessage> getParserForType() {
      return PARSER;
    }

    @Override
    public HostMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface InstructionOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.mosh4j.protocol.host.Instruction)
      com.google.protobuf.GeneratedMessage.
          ExtendableMessageOrBuilder<Instruction> {
  }
  /**
   * Protobuf type {@code org.mosh4j.protocol.host.Instruction}
   */
  public static final class Instruction extends
      com.google.protobuf.GeneratedMessage.ExtendableMessage<
        Instruction> implements
      // @@protoc_insertion_point(message_implements:org.mosh4j.protocol.host.Instruction)
      InstructionOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 35,
        /* patch= */ 1,
        /* suffix= */ "",
        "Instruction");
    }
    // Use Instruction.newBuilder() to construct.
    private Instruction(ExtendableBuilder<Instruction, ?> builder) {
      super(builder);
    }
    private Instruction() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Hostinput.internal_static_org_mosh4j_protocol_host_Instruction_descriptor;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
      return Hostinput.internal_static_org_mosh4j_protocol_host_Instruction_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Hostinput.internal_static_org_mosh4j_protocol_host_Instruction_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Instruction.class, Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!extensionsAreInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      ExtensionSerializer
          extensionWriter = newExtensionSerializer();
      extensionWriter.writeUntil(536870912, output);
      getUnknownFields().writeTo(output);
    }
    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += extensionsSerializedSize();
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Instruction)) {
        return super.equals(obj);
      }
      Instruction other = (Instruction) obj;

      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      if (!getExtensionFields().equals(other.getExtensionFields()))
        return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = hashFields(hash, getExtensionFields());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Instruction parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Instruction parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Instruction parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Instruction parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Instruction parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Instruction parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Instruction parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static Instruction parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static Instruction parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static Instruction parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Instruction parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static Instruction parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Instruction prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.mosh4j.protocol.host.Instruction}
     */
    public static final class Builder extends
        ExtendableBuilder<
          Instruction, Builder> implements
        // @@protoc_insertion_point(builder_implements:org.mosh4j.protocol.host.Instruction)
        InstructionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Hostinput.internal_static_org_mosh4j_protocol_host_Instruction_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Hostinput.internal_static_org_mosh4j_protocol_host_Instruction_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Instruction.class, Builder.class);
      }

      // Construct using org.mosh4j.protocol.host.Hostinput.Instruction.newBuilder()
      private Builder() {

      }

      private Builder(
          BuilderParent parent) {
        super(parent);

      }
      @Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Hostinput.internal_static_org_mosh4j_protocol_host_Instruction_descriptor;
      }

      @Override
      public Instruction getDefaultInstanceForType() {
        return Instruction.getDefaultInstance();
      }

      @Override
      public Instruction build() {
        Instruction result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public Instruction buildPartial() {
        Instruction result = new Instruction(this);
        onBuilt();
        return result;
      }

      public <Type> Builder setExtension(
          GeneratedExtension<
              Instruction, Type> extension,
          Type value) {
        return super.setExtension(extension, value);
      }
      public <Type> Builder setExtension(
          GeneratedExtension<
              Instruction, java.util.List<Type>> extension,
          int index, Type value) {
        return super.setExtension(extension, index, value);
      }
      public <Type> Builder addExtension(
          GeneratedExtension<
              Instruction, java.util.List<Type>> extension,
          Type value) {
        return super.addExtension(extension, value);
      }
      public <Type> Builder clearExtension(
          GeneratedExtension<
              Instruction, Type> extension) {
        return super.clearExtension(extension);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Instruction) {
          return mergeFrom((Instruction)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Instruction other) {
        if (other == Instruction.getDefaultInstance()) return this;
        this.mergeExtensionFields(other);
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        if (!extensionsAreInitialized()) {
          return false;
        }
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }

      // @@protoc_insertion_point(builder_scope:org.mosh4j.protocol.host.Instruction)
    }

    // @@protoc_insertion_point(class_scope:org.mosh4j.protocol.host.Instruction)
    private static final Instruction DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Instruction();
    }

    public static Instruction getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Instruction>
        PARSER = new com.google.protobuf.AbstractParser<Instruction>() {
      @Override
      public Instruction parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Instruction> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Instruction> getParserForType() {
      return PARSER;
    }

    @Override
    public Instruction getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface HostBytesOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.mosh4j.protocol.host.HostBytes)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional bytes hoststring = 4;</code>
     * @return Whether the hoststring field is set.
     */
    boolean hasHoststring();
    /**
     * <code>optional bytes hoststring = 4;</code>
     * @return The hoststring.
     */
    com.google.protobuf.ByteString getHoststring();
  }
  /**
   * Protobuf type {@code org.mosh4j.protocol.host.HostBytes}
   */
  public static final class HostBytes extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:org.mosh4j.protocol.host.HostBytes)
      HostBytesOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 35,
        /* patch= */ 1,
        /* suffix= */ "",
        "HostBytes");
    }
    // Use HostBytes.newBuilder() to construct.
    private HostBytes(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private HostBytes() {
      hoststring_ = com.google.protobuf.ByteString.EMPTY;
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Hostinput.internal_static_org_mosh4j_protocol_host_HostBytes_descriptor;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
      return Hostinput.internal_static_org_mosh4j_protocol_host_HostBytes_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Hostinput.internal_static_org_mosh4j_protocol_host_HostBytes_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              HostBytes.class, Builder.class);
    }

    private int bitField0_;
    public static final int HOSTSTRING_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString hoststring_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>optional bytes hoststring = 4;</code>
     * @return Whether the hoststring field is set.
     */
    @Override
    public boolean hasHoststring() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional bytes hoststring = 4;</code>
     * @return The hoststring.
     */
    @Override
    public com.google.protobuf.ByteString getHoststring() {
      return hoststring_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeBytes(4, hoststring_);
      }
      getUnknownFields().writeTo(output);
    }
    private int computeSerializedSize_0() {
      int size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, hoststring_);
      }
      return size;
    }
    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += computeSerializedSize_0();
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof HostBytes)) {
        return super.equals(obj);
      }
      HostBytes other = (HostBytes) obj;

      if (hasHoststring() != other.hasHoststring()) return false;
      if (hasHoststring()) {
        if (!getHoststring()
            .equals(other.getHoststring())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasHoststring()) {
        hash = (37 * hash) + HOSTSTRING_FIELD_NUMBER;
        hash = (53 * hash) + getHoststring().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static HostBytes parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static HostBytes parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static HostBytes parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static HostBytes parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static HostBytes parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static HostBytes parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static HostBytes parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static HostBytes parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static HostBytes parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static HostBytes parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static HostBytes parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static HostBytes parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(HostBytes prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.mosh4j.protocol.host.HostBytes}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.mosh4j.protocol.host.HostBytes)
        HostBytesOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Hostinput.internal_static_org_mosh4j_protocol_host_HostBytes_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Hostinput.internal_static_org_mosh4j_protocol_host_HostBytes_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                HostBytes.class, Builder.class);
      }

      // Construct using org.mosh4j.protocol.host.Hostinput.HostBytes.newBuilder()
      private Builder() {

      }

      private Builder(
          BuilderParent parent) {
        super(parent);

      }
      @Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        hoststring_ = com.google.protobuf.ByteString.EMPTY;
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Hostinput.internal_static_org_mosh4j_protocol_host_HostBytes_descriptor;
      }

      @Override
      public HostBytes getDefaultInstanceForType() {
        return HostBytes.getDefaultInstance();
      }

      @Override
      public HostBytes build() {
        HostBytes result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public HostBytes buildPartial() {
        HostBytes result = new HostBytes(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(HostBytes result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.hoststring_ = hoststring_;
          to_bitField0_ |= 0x00000001;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof HostBytes) {
          return mergeFrom((HostBytes)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(HostBytes other) {
        if (other == HostBytes.getDefaultInstance()) return this;
        if (other.hasHoststring()) {
          setHoststring(other.getHoststring());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 34: {
                hoststring_ = input.readBytes();
                bitField0_ |= 0x00000001;
                break;
              } // case 34
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.ByteString hoststring_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes hoststring = 4;</code>
       * @return Whether the hoststring field is set.
       */
      @Override
      public boolean hasHoststring() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional bytes hoststring = 4;</code>
       * @return The hoststring.
       */
      @Override
      public com.google.protobuf.ByteString getHoststring() {
        return hoststring_;
      }
      /**
       * <code>optional bytes hoststring = 4;</code>
       * @param value The hoststring to set.
       * @return This builder for chaining.
       */
      public Builder setHoststring(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        hoststring_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes hoststring = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearHoststring() {
        bitField0_ = (bitField0_ & ~0x00000001);
        hoststring_ = getDefaultInstance().getHoststring();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:org.mosh4j.protocol.host.HostBytes)
    }

    // @@protoc_insertion_point(class_scope:org.mosh4j.protocol.host.HostBytes)
    private static final HostBytes DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new HostBytes();
    }

    public static HostBytes getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<HostBytes>
        PARSER = new com.google.protobuf.AbstractParser<HostBytes>() {
      @Override
      public HostBytes parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<HostBytes> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<HostBytes> getParserForType() {
      return PARSER;
    }

    @Override
    public HostBytes getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ResizeMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.mosh4j.protocol.host.ResizeMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 width = 5;</code>
     * @return Whether the width field is set.
     */
    boolean hasWidth();
    /**
     * <code>optional int32 width = 5;</code>
     * @return The width.
     */
    int getWidth();

    /**
     * <code>optional int32 height = 6;</code>
     * @return Whether the height field is set.
     */
    boolean hasHeight();
    /**
     * <code>optional int32 height = 6;</code>
     * @return The height.
     */
    int getHeight();
  }
  /**
   * Protobuf type {@code org.mosh4j.protocol.host.ResizeMessage}
   */
  public static final class ResizeMessage extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:org.mosh4j.protocol.host.ResizeMessage)
      ResizeMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 35,
        /* patch= */ 1,
        /* suffix= */ "",
        "ResizeMessage");
    }
    // Use ResizeMessage.newBuilder() to construct.
    private ResizeMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private ResizeMessage() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Hostinput.internal_static_org_mosh4j_protocol_host_ResizeMessage_descriptor;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
      return Hostinput.internal_static_org_mosh4j_protocol_host_ResizeMessage_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Hostinput.internal_static_org_mosh4j_protocol_host_ResizeMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ResizeMessage.class, Builder.class);
    }

    private int bitField0_;
    public static final int WIDTH_FIELD_NUMBER = 5;
    private int width_ = 0;
    /**
     * <code>optional int32 width = 5;</code>
     * @return Whether the width field is set.
     */
    @Override
    public boolean hasWidth() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional int32 width = 5;</code>
     * @return The width.
     */
    @Override
    public int getWidth() {
      return width_;
    }

    public static final int HEIGHT_FIELD_NUMBER = 6;
    private int height_ = 0;
    /**
     * <code>optional int32 height = 6;</code>
     * @return Whether the height field is set.
     */
    @Override
    public boolean hasHeight() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional int32 height = 6;</code>
     * @return The height.
     */
    @Override
    public int getHeight() {
      return height_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt32(5, width_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeInt32(6, height_);
      }
      getUnknownFields().writeTo(output);
    }
    private int computeSerializedSize_0() {
      int size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, width_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, height_);
      }
      return size;
    }
    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += computeSerializedSize_0();
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ResizeMessage)) {
        return super.equals(obj);
      }
      ResizeMessage other = (ResizeMessage) obj;

      if (hasWidth() != other.hasWidth()) return false;
      if (hasWidth()) {
        if (getWidth()
            != other.getWidth()) return false;
      }
      if (hasHeight() != other.hasHeight()) return false;
      if (hasHeight()) {
        if (getHeight()
            != other.getHeight()) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasWidth()) {
        hash = (37 * hash) + WIDTH_FIELD_NUMBER;
        hash = (53 * hash) + getWidth();
      }
      if (hasHeight()) {
        hash = (37 * hash) + HEIGHT_FIELD_NUMBER;
        hash = (53 * hash) + getHeight();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ResizeMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ResizeMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ResizeMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ResizeMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ResizeMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ResizeMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ResizeMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static ResizeMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static ResizeMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static ResizeMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ResizeMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static ResizeMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ResizeMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.mosh4j.protocol.host.ResizeMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.mosh4j.protocol.host.ResizeMessage)
        ResizeMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Hostinput.internal_static_org_mosh4j_protocol_host_ResizeMessage_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Hostinput.internal_static_org_mosh4j_protocol_host_ResizeMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ResizeMessage.class, Builder.class);
      }

      // Construct using org.mosh4j.protocol.host.Hostinput.ResizeMessage.newBuilder()
      private Builder() {

      }

      private Builder(
          BuilderParent parent) {
        super(parent);

      }
      @Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        width_ = 0;
        height_ = 0;
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Hostinput.internal_static_org_mosh4j_protocol_host_ResizeMessage_descriptor;
      }

      @Override
      public ResizeMessage getDefaultInstanceForType() {
        return ResizeMessage.getDefaultInstance();
      }

      @Override
      public ResizeMessage build() {
        ResizeMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public ResizeMessage buildPartial() {
        ResizeMessage result = new ResizeMessage(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(ResizeMessage result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.width_ = width_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.height_ = height_;
          to_bitField0_ |= 0x00000002;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ResizeMessage) {
          return mergeFrom((ResizeMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ResizeMessage other) {
        if (other == ResizeMessage.getDefaultInstance()) return this;
        if (other.hasWidth()) {
          setWidth(other.getWidth());
        }
        if (other.hasHeight()) {
          setHeight(other.getHeight());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 40: {
                width_ = input.readInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 40
              case 48: {
                height_ = input.readInt32();
                bitField0_ |= 0x00000002;
                break;
              } // case 48
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int width_ ;
      /**
       * <code>optional int32 width = 5;</code>
       * @return Whether the width field is set.
       */
      @Override
      public boolean hasWidth() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional int32 width = 5;</code>
       * @return The width.
       */
      @Override
      public int getWidth() {
        return width_;
      }
      /**
       * <code>optional int32 width = 5;</code>
       * @param value The width to set.
       * @return This builder for chaining.
       */
      public Builder setWidth(int value) {

        width_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 width = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearWidth() {
        bitField0_ = (bitField0_ & ~0x00000001);
        width_ = 0;
        onChanged();
        return this;
      }

      private int height_ ;
      /**
       * <code>optional int32 height = 6;</code>
       * @return Whether the height field is set.
       */
      @Override
      public boolean hasHeight() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional int32 height = 6;</code>
       * @return The height.
       */
      @Override
      public int getHeight() {
        return height_;
      }
      /**
       * <code>optional int32 height = 6;</code>
       * @param value The height to set.
       * @return This builder for chaining.
       */
      public Builder setHeight(int value) {

        height_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 height = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearHeight() {
        bitField0_ = (bitField0_ & ~0x00000002);
        height_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:org.mosh4j.protocol.host.ResizeMessage)
    }

    // @@protoc_insertion_point(class_scope:org.mosh4j.protocol.host.ResizeMessage)
    private static final ResizeMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ResizeMessage();
    }

    public static ResizeMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ResizeMessage>
        PARSER = new com.google.protobuf.AbstractParser<ResizeMessage>() {
      @Override
      public ResizeMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ResizeMessage> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<ResizeMessage> getParserForType() {
      return PARSER;
    }

    @Override
    public ResizeMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface EchoAckOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.mosh4j.protocol.host.EchoAck)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional uint64 echo_ack_num = 8;</code>
     * @return Whether the echoAckNum field is set.
     */
    boolean hasEchoAckNum();
    /**
     * <code>optional uint64 echo_ack_num = 8;</code>
     * @return The echoAckNum.
     */
    long getEchoAckNum();
  }
  /**
   * Protobuf type {@code org.mosh4j.protocol.host.EchoAck}
   */
  public static final class EchoAck extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:org.mosh4j.protocol.host.EchoAck)
      EchoAckOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 35,
        /* patch= */ 1,
        /* suffix= */ "",
        "EchoAck");
    }
    // Use EchoAck.newBuilder() to construct.
    private EchoAck(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private EchoAck() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Hostinput.internal_static_org_mosh4j_protocol_host_EchoAck_descriptor;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
      return Hostinput.internal_static_org_mosh4j_protocol_host_EchoAck_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Hostinput.internal_static_org_mosh4j_protocol_host_EchoAck_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              EchoAck.class, Builder.class);
    }

    private int bitField0_;
    public static final int ECHO_ACK_NUM_FIELD_NUMBER = 8;
    private long echoAckNum_ = 0L;
    /**
     * <code>optional uint64 echo_ack_num = 8;</code>
     * @return Whether the echoAckNum field is set.
     */
    @Override
    public boolean hasEchoAckNum() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional uint64 echo_ack_num = 8;</code>
     * @return The echoAckNum.
     */
    @Override
    public long getEchoAckNum() {
      return echoAckNum_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeUInt64(8, echoAckNum_);
      }
      getUnknownFields().writeTo(output);
    }
    private int computeSerializedSize_0() {
      int size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(8, echoAckNum_);
      }
      return size;
    }
    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += computeSerializedSize_0();
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof EchoAck)) {
        return super.equals(obj);
      }
      EchoAck other = (EchoAck) obj;

      if (hasEchoAckNum() != other.hasEchoAckNum()) return false;
      if (hasEchoAckNum()) {
        if (getEchoAckNum()
            != other.getEchoAckNum()) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasEchoAckNum()) {
        hash = (37 * hash) + ECHO_ACK_NUM_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getEchoAckNum());
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static EchoAck parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static EchoAck parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static EchoAck parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static EchoAck parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static EchoAck parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static EchoAck parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static EchoAck parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static EchoAck parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static EchoAck parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static EchoAck parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static EchoAck parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static EchoAck parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(EchoAck prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.mosh4j.protocol.host.EchoAck}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.mosh4j.protocol.host.EchoAck)
        EchoAckOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Hostinput.internal_static_org_mosh4j_protocol_host_EchoAck_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Hostinput.internal_static_org_mosh4j_protocol_host_EchoAck_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                EchoAck.class, Builder.class);
      }

      // Construct using org.mosh4j.protocol.host.Hostinput.EchoAck.newBuilder()
      private Builder() {

      }

      private Builder(
          BuilderParent parent) {
        super(parent);

      }
      @Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        echoAckNum_ = 0L;
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Hostinput.internal_static_org_mosh4j_protocol_host_EchoAck_descriptor;
      }

      @Override
      public EchoAck getDefaultInstanceForType() {
        return EchoAck.getDefaultInstance();
      }

      @Override
      public EchoAck build() {
        EchoAck result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public EchoAck buildPartial() {
        EchoAck result = new EchoAck(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(EchoAck result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.echoAckNum_ = echoAckNum_;
          to_bitField0_ |= 0x00000001;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof EchoAck) {
          return mergeFrom((EchoAck)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(EchoAck other) {
        if (other == EchoAck.getDefaultInstance()) return this;
        if (other.hasEchoAckNum()) {
          setEchoAckNum(other.getEchoAckNum());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 64: {
                echoAckNum_ = input.readUInt64();
                bitField0_ |= 0x00000001;
                break;
              } // case 64
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private long echoAckNum_ ;
      /**
       * <code>optional uint64 echo_ack_num = 8;</code>
       * @return Whether the echoAckNum field is set.
       */
      @Override
      public boolean hasEchoAckNum() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional uint64 echo_ack_num = 8;</code>
       * @return The echoAckNum.
       */
      @Override
      public long getEchoAckNum() {
        return echoAckNum_;
      }
      /**
       * <code>optional uint64 echo_ack_num = 8;</code>
       * @param value The echoAckNum to set.
       * @return This builder for chaining.
       */
      public Builder setEchoAckNum(long value) {

        echoAckNum_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 echo_ack_num = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearEchoAckNum() {
        bitField0_ = (bitField0_ & ~0x00000001);
        echoAckNum_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:org.mosh4j.protocol.host.EchoAck)
    }

    // @@protoc_insertion_point(class_scope:org.mosh4j.protocol.host.EchoAck)
    private static final EchoAck DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new EchoAck();
    }

    public static EchoAck getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<EchoAck>
        PARSER = new com.google.protobuf.AbstractParser<EchoAck>() {
      @Override
      public EchoAck parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<EchoAck> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<EchoAck> getParserForType() {
      return PARSER;
    }

    @Override
    public EchoAck getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public static final int HOSTBYTES_FIELD_NUMBER = 2;
  /**
   * <code>extend .org.mosh4j.protocol.host.Instruction { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      Instruction,
      HostBytes> hostbytes = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        HostBytes.class,
        HostBytes.getDefaultInstance());
  public static final int RESIZE_FIELD_NUMBER = 3;
  /**
   * <code>extend .org.mosh4j.protocol.host.Instruction { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      Instruction,
      ResizeMessage> resize = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        ResizeMessage.class,
        ResizeMessage.getDefaultInstance());
  public static final int ECHOACK_FIELD_NUMBER = 7;
  /**
   * <code>extend .org.mosh4j.protocol.host.Instruction { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      Instruction,
      EchoAck> echoack = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        EchoAck.class,
        EchoAck.getDefaultInstance());
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_mosh4j_protocol_host_HostMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_mosh4j_protocol_host_HostMessage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_mosh4j_protocol_host_Instruction_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_mosh4j_protocol_host_Instruction_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_mosh4j_protocol_host_HostBytes_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_mosh4j_protocol_host_HostBytes_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_mosh4j_protocol_host_ResizeMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_mosh4j_protocol_host_ResizeMessage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_mosh4j_protocol_host_EchoAck_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_mosh4j_protocol_host_EchoAck_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static final com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\017hostinput.proto\022\030org.mosh4j.protocol.h" +
      "ost\"I\n\013HostMessage\022:\n\013instruction\030\001 \003(\0132" +
      "%.org.mosh4j.protocol.host.Instruction\"\027" +
      "\n\013Instruction*\010\010\002\020\200\200\200\200\002\"\037\n\tHostBytes\022\022\n\n" +
      "hoststring\030\004 \001(\014\".\n\rResizeMessage\022\r\n\005wid" +
      "th\030\005 \001(\005\022\016\n\006height\030\006 \001(\005\"\037\n\007EchoAck\022\024\n\014e" +
      "cho_ack_num\030\010 \001(\004:]\n\thostbytes\022%.org.mos" +
      "h4j.protocol.host.Instruction\030\002 \001(\0132#.or" +
      "g.mosh4j.protocol.host.HostBytes:^\n\006resi" +
      "ze\022%.org.mosh4j.protocol.host.Instructio" +
      "n\030\003 \001(\0132\'.org.mosh4j.protocol.host.Resiz" +
      "eMessage:Y\n\007echoack\022%.org.mosh4j.protoco" +
      "l.host.Instruction\030\007 \001(\0132!.org.mosh4j.pr" +
      "otocol.host.EchoAckB\002H\003"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_org_mosh4j_protocol_host_HostMessage_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_org_mosh4j_protocol_host_HostMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_org_mosh4j_protocol_host_HostMessage_descriptor,
        new String[] { "Instruction", });
    internal_static_org_mosh4j_protocol_host_Instruction_descriptor =
      getDescriptor().getMessageType(1);
    internal_static_org_mosh4j_protocol_host_Instruction_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_org_mosh4j_protocol_host_Instruction_descriptor,
        new String[] { });
    internal_static_org_mosh4j_protocol_host_HostBytes_descriptor =
      getDescriptor().getMessageType(2);
    internal_static_org_mosh4j_protocol_host_HostBytes_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_org_mosh4j_protocol_host_HostBytes_descriptor,
        new String[] { "Hoststring", });
    internal_static_org_mosh4j_protocol_host_ResizeMessage_descriptor =
      getDescriptor().getMessageType(3);
    internal_static_org_mosh4j_protocol_host_ResizeMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_org_mosh4j_protocol_host_ResizeMessage_descriptor,
        new String[] { "Width", "Height", });
    internal_static_org_mosh4j_protocol_host_EchoAck_descriptor =
      getDescriptor().getMessageType(4);
    internal_static_org_mosh4j_protocol_host_EchoAck_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_org_mosh4j_protocol_host_EchoAck_descriptor,
        new String[] { "EchoAckNum", });
    hostbytes.internalInit(descriptor.getExtension(0));
    resize.internalInit(descriptor.getExtension(1));
    echoack.internalInit(descriptor.getExtension(2));
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
