version: '3.8'
services:
  webdav-digest:
    container_name: bytemark-webdav-digest
    image: bytemark/webdav
    ports:
      - "18081:80"
    environment:
      #HTTP使用Digest,HTTPS使用Basic
      AUTH_TYPE: Digest
      USERNAME: test
      PASSWORD: 123456

