name: Macos_arm64_1

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-15

    steps:

      - name: 检出项目
        uses: actions/checkout@v4
        
      - name: 下载工具包
        run: |
          curl -s "https://get.sdkman.io" | bash
          source "$HOME/.sdkman/bin/sdkman-init.sh"
          echo "SDKMAN_DIR=$HOME/.sdkman" >> $GITHUB_ENV
          echo "$HOME/.sdkman/bin" >> $GITHUB_PATH
          
      - name: 下载jdk
        run: |
          source "$HOME/.sdkman/bin/sdkman-init.sh"
          sdk install java 25.ea.36-open
          sdk use java 25.ea.36-open
          java -version

      - name:  处理前置依赖
        run: |
          source "$HOME/.sdkman/bin/sdkman-init.sh"
           # 处理base依赖
          git clone --depth 1 --branch v1.0.3  https://github.com/oyzh1994/base.git
          cd base
          mvn clean install -DskipTests
          cd ..
          rm -rf base
          
          # 处理fx-base依赖
          git clone --depth 1 --branch v1.3.6 https://github.com/oyzh1994/fx-base.git
          cd fx-base
          mvn clean install -DskipTests
          cd ..
          rm -rf fx-base

      - name: 打包项目Jar
        run: |
          source "$HOME/.sdkman/bin/sdkman-init.sh"
          mvn -X clean package -DskipTests

      - name: 执行打包
        run: |
          # 确保SDKMAN环境变量被正确加载
          source "$HOME/.sdkman/bin/sdkman-init.sh"
          chmod +x ./package/pack.sh
          ./package/pack.sh

      - name: 显示项目结构
        run: |
          brew install tree
          echo "--- 项目目录结构 ---"
          tree -L 3
          
      - name: 列举生成的构建物
        run: ls -lh dist

      - name: 上传构建物
        uses: actions/upload-artifact@v4
        with:
          name: easyshell-pkg
          path: dist/*.pkg
