name: Windows_amd64_pkg

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: 检出项目
        uses: actions/checkout@v4
      - name: 下载jdk
        uses: actions/setup-java@v4
        with:
          java-version: '24.0.2'
          distribution: 'temurin'  # Windows上推荐使用temurin发行版
          architecture: x64
          cache: 'maven'  # 缓存Maven依赖
      - name: 验证Java
        run: |
          java -version
          echo "当前 JAVA_HOME 路径：$env:JAVA_HOME"
      - name:  处理前置依赖
        run: |
          # 处理base依赖
          git clone --depth 1 --branch v1.0.2 https://github.com/oyzh1994/base.git
          cd base
          mvn clean install -DskipTests
          cd ..
          rm -rf base
          # 处理fx-base依赖
          git clone --depth 1 --branch v1.3.5 https://github.com/oyzh1994/fx-base.git
          cd fx-base
          mvn clean install -DskipTests
          cd ..
          rm -rf fx-base
        shell: bash  # 使用bash兼容语法
      - name: 执行打包
        run: |
          chmod +x ./package/pack.bat
          ./package/pack.sh windows_exe,windows_msi
      - name: 显示项目结构
        run: |
          # Windows上通过choco安装tree
          choco install tree
          echo "--- 项目目录结构 ---"
          tree /f /a
        shell: bash
      - name: 上传pkg构建物
        uses: actions/upload-artifact@v4
        with:
          name: EasyShell.exe
          path: dist/*.exe
      - name: 上传dmg构建物
        uses: actions/upload-artifact@v4
        with:
          name: EasyShell.msi
          path: dist/*.msi